"""SQLAlchemy-backed DailyReport repository.

Stores idempotent daily reports (one per user per date via UNIQUE constraint).
Reports are generated by ``services/report_service.py`` and written here.

Table schema matches the Alembic migration (0001_create_core_tables).
"""

from __future__ import annotations

import json
from datetime import date
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects.sqlite import insert as sqlite_upsert
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from mindflow.domain.ids import new_id

# ── Table definition (matches migration 0001_create_core_tables) ─────

metadata = sa.MetaData()

daily_reports = sa.Table(
    "daily_reports",
    metadata,
    sa.Column("id", sa.Text(), primary_key=True),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.Column("date", sa.Text(), nullable=False),
    sa.Column(
        "total_focus_min",
        sa.Float(),
        nullable=False,
        server_default=sa.text("0.0"),
    ),
    sa.Column(
        "total_distraction_min",
        sa.Float(),
        nullable=False,
        server_default=sa.text("0.0"),
    ),
    sa.Column(
        "focus_score",
        sa.Float(),
        nullable=False,
        server_default=sa.text("0.0"),
    ),
    sa.Column("top_apps_json", sa.Text(), nullable=True),
    sa.Column(
        "switch_frequency",
        sa.Float(),
        nullable=False,
        server_default=sa.text("0.0"),
    ),
    sa.Column("pattern_summary", sa.Text(), nullable=True),
    sa.Column(
        "created_at",
        sa.Text(),
        nullable=False,
        server_default=sa.text("(strftime('%Y-%m-%dT%H:%M:%SZ','now'))"),
    ),
    sa.UniqueConstraint("user_id", "date"),
)


# ── Repository ────────────────────────────────────────────────────────


class SQLAlchemyDailyReportRepository:
    """Daily report repository backed by SQLAlchemy Core + async SQLite.

    Uses SQLite UPSERT (ON CONFLICT DO UPDATE) for idempotent writes.
    """

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
    ) -> None:
        self._session_factory = session_factory

    # ── Public API ────────────────────────────────────────────────────

    async def upsert(
        self,
        report: dict[str, Any],
    ) -> dict[str, Any]:
        """Insert or update a daily report (idempotent via UNIQUE(user_id,date)).

        If a report for the same ``user_id`` + ``date`` already exists,
        its fields are updated with the new values.

        Args:
            report: Report data dict with keys:
                ``user_id``, ``date``, ``total_focus_min``,
                ``total_distraction_min``, ``focus_score``,
                ``top_apps`` (list[AppUsage] or list[dict], optional),
                ``switch_frequency``, ``pattern_summary`` (optional).

        Returns:
            The upserted report dict.
        """
        rid = report.get("id") or new_id()
        top_apps = report.get("top_apps")
        top_apps_json = json.dumps(
            [a.to_dict() if hasattr(a, "to_dict") else a for a in top_apps]
            if top_apps
            else None,
            ensure_ascii=False,
        )

        values = {
            "id": rid,
            "user_id": report["user_id"],
            "date": report["date"],
            "total_focus_min": report.get("total_focus_min", 0.0),
            "total_distraction_min": report.get("total_distraction_min", 0.0),
            "focus_score": report.get("focus_score", 0.0),
            "top_apps_json": top_apps_json,
            "switch_frequency": report.get("switch_frequency", 0.0),
            "pattern_summary": report.get("pattern_summary"),
        }

        stmt = sqlite_upsert(daily_reports).values(**values)
        stmt = stmt.on_conflict_do_update(
            index_elements=["user_id", "date"],
            set_={
                "total_focus_min": stmt.excluded.total_focus_min,
                "total_distraction_min": stmt.excluded.total_distraction_min,
                "focus_score": stmt.excluded.focus_score,
                "top_apps_json": stmt.excluded.top_apps_json,
                "switch_frequency": stmt.excluded.switch_frequency,
                "pattern_summary": stmt.excluded.pattern_summary,
            },
        )

        async with self._session_factory() as session, session.begin():
            await session.execute(stmt)

        return {
            "id": rid,
            "user_id": report["user_id"],
            "date": report["date"],
            "total_focus_min": values["total_focus_min"],
            "total_distraction_min": values["total_distraction_min"],
            "focus_score": values["focus_score"],
            "top_apps": report.get("top_apps"),
            "switch_frequency": values["switch_frequency"],
            "pattern_summary": values["pattern_summary"],
        }

    async def get_by_date(
        self,
        user_id: int,
        target_date: date,
    ) -> dict[str, Any] | None:
        """Return the daily report for *user_id* on *target_date*, or None.

        Args:
            user_id: User identifier.
            target_date: The report date.

        Returns:
            A report dict, or None if no report exists for that date.
        """
        stmt = (
            sa.select(daily_reports)
            .where(
                daily_reports.c.user_id == user_id,
                daily_reports.c.date == target_date.isoformat(),
            )
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            row = result.fetchone()
        return _row_to_dict(row) if row is not None else None

    async def query_range(
        self,
        user_id: int,
        start_date: date,
        end_date: date,
    ) -> list[dict[str, Any]]:
        """Return daily reports in [*start_date*, *end_date*] ordered by date.

        Args:
            user_id: User identifier.
            start_date: Inclusive start date.
            end_date: Inclusive end date.

        Returns:
            A list of report dicts sorted by date ascending.
        """
        stmt = (
            sa.select(daily_reports)
            .where(
                daily_reports.c.user_id == user_id,
                daily_reports.c.date >= start_date.isoformat(),
                daily_reports.c.date <= end_date.isoformat(),
            )
            .order_by(daily_reports.c.date.asc())
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            return [_row_to_dict(row) for row in result.fetchall()]

    async def exists_for_date(self, user_id: int, target_date: date) -> bool:
        """Return True if a report already exists for *user_id* on *target_date*."""
        stmt = (
            sa.select(sa.func.count())
            .select_from(daily_reports)
            .where(
                daily_reports.c.user_id == user_id,
                daily_reports.c.date == target_date.isoformat(),
            )
        )
        async with self._session_factory() as session:
            result = await session.execute(stmt)
            count: int = result.scalar() or 0
            return count > 0

    def __repr__(self) -> str:
        return "<SQLAlchemyDailyReportRepository>"


# ── Serialisation helpers ─────────────────────────────────────────────


def _row_to_dict(row: sa.Row[Any]) -> dict[str, Any]:
    """Convert a database row (``daily_reports``) to a plain dict."""
    top_apps = None
    if row.top_apps_json:
        try:
            top_apps = json.loads(row.top_apps_json)
        except (json.JSONDecodeError, TypeError):
            top_apps = None

    return {
        "id": row.id,
        "user_id": row.user_id,
        "date": row.date,
        "total_focus_min": row.total_focus_min,
        "total_distraction_min": row.total_distraction_min,
        "focus_score": row.focus_score,
        "top_apps": top_apps,
        "switch_frequency": row.switch_frequency,
        "pattern_summary": row.pattern_summary,
        "created_at": row.created_at,
    }
