/**
 * OpenAPI contract drift gate (Todo 5).
 *
 * Run with: npx tsx tests/api-schema-drift.test.ts
 * Wired as: npm run check:api-drift
 * No test framework: plain node asserts, deterministic, zero clocks.
 *
 * The canonical generator (frontend `npm run generate:api`) runs:
 *   python ../backend-next/scripts/export_openapi.py <dst>/openapi.json
 *   openapi-typescript <dst>/openapi.json -o <dst>/api-schema.ts
 *
 * This gate regenerates the schema into a TEMP directory (never overwriting
 * the tracked file) and byte-compares the result against the committed
 * `src/generated/api-schema.ts`. It additionally proves generation is
 * deterministic (two runs byte-identical) and that the contract locks the
 * canonical response models and exact data-state / prediction-status enums.
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const TEST_DIR = dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = resolve(TEST_DIR, "..");
const BACKEND_EXPORT_SCRIPT = resolve(FRONTEND_ROOT, "../backend-next/scripts/export_openapi.py");
const OPENAPI_TYPESCRIPT_CLI = resolve(FRONTEND_ROOT, "node_modules/openapi-typescript/bin/cli.js");
const TRACKED_SCHEMA = resolve(FRONTEND_ROOT, "src/generated/api-schema.ts");

/**
 * Git may check out text files with CRLF on Windows (core.autocrlf) while the
 * generator always writes LF. Both describe the same blob, so the drift
 * comparison normalizes line endings on both sides; the determinism check
 * stays a raw byte compare of two fresh generator runs (both LF).
 */
function normalizeLineEndings(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

/** Run the generator pipeline into *outDir*, returning the api-schema.ts text. */
function runGenerator(outDir: string): string {
  const openapiJson = join(outDir, "openapi.json");
  const schemaTs = join(outDir, "api-schema.ts");
  // Timeouts turn a hung generator (stuck backend import, dead CLI) into a
  // clean test failure instead of an indefinite wait.
  execFileSync("python", [BACKEND_EXPORT_SCRIPT, openapiJson], {
    cwd: FRONTEND_ROOT,
    stdio: "pipe",
    timeout: 120_000,
  });
  execFileSync(process.execPath, [OPENAPI_TYPESCRIPT_CLI, openapiJson, "-o", schemaTs], {
    cwd: FRONTEND_ROOT,
    stdio: "pipe",
    timeout: 120_000,
  });
  return readFileSync(schemaTs, "utf8");
}

// Canonical contract tokens the committed schema MUST lock (structural, machine-consumed).
const REQUIRED_CONTRACT_TOKENS: ReadonlyArray<string> = [
  "FocusPredictionResponse: {",
  "DailyReportResponse: {",
  "WeeklyReportResponse: {",
  // Exact six-value prediction status literal (domain/prediction.py).
  `status: "ready" | "no_model" | "no_data" | "stale" | "schema_mismatch" | "inference_error";`,
  // Exact six-value daily data-state literal (api/schemas.py).
  `data_state: "ready" | "no_activity" | "events_only" | "neutral_only" | "no_focus" | "future";`,
  // Exact four-value weekly data-state literal (api/schemas.py).
  `data_state: "ready" | "partial" | "no_activity" | "future";`,
  // Exact baseline summary response model with canonical V2 means (Todo 10).
  "BaselineSummary: {",
  "mean_app_switch_count: number | null;",
  "mean_active_seconds_ratio: number | null;",
  "mean_idle_ratio: number | null;",
  "switch_frequency: number | null;",
  "productivity_ratio: number | null;",
];

let passed = 0;
const failures: string[] = [];

function test(name: string, fn: () => void): void {
  try {
    fn();
    passed += 1;
  } catch (error) {
    failures.push(`${name}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

const tmpDir = mkdtempSync(join(tmpdir(), "api-schema-drift-"));

try {
  const tracked = readFileSync(TRACKED_SCHEMA, "utf8");

  test("generation is deterministic: two runs are byte-identical", () => {
    const first = runGenerator(join(tmpDir, "gen-a"));
    const second = runGenerator(join(tmpDir, "gen-b"));
    assert.equal(first, second, "two generator runs produced different bytes");
  });

  test("tracked schema matches the freshly generated output (no drift)", () => {
    const generated = normalizeLineEndings(runGenerator(join(tmpDir, "gen-c")));
    const normalizedTracked = normalizeLineEndings(tracked);
    assert.equal(
      normalizedTracked,
      generated,
      [
        "tracked src/generated/api-schema.ts drifted from the backend OpenAPI contract.",
        "Regenerate with: npm run generate:api",
        `tracked bytes:   ${normalizedTracked.length}`,
        `generated bytes: ${generated.length}`,
      ].join("\n"),
    );
  });

  test("tracked schema locks the canonical prediction/report response models and enums", () => {
    for (const token of REQUIRED_CONTRACT_TOKENS) {
      assert.ok(
        tracked.includes(token),
        `tracked schema is missing contract token: ${token}`,
      );
    }
  });
} finally {
  rmSync(tmpDir, { recursive: true, force: true });
}

if (failures.length > 0) {
  console.error(`\n${failures.length} test(s) FAILED:`);
  for (const failure of failures) console.error(`  - ${failure}`);
  console.error(`${passed} passed, ${failures.length} failed`);
  process.exit(1);
}
console.log(`api-schema-drift: ${passed} tests passed`);
